### PR TITLE
Use apns-conf from LOS 16.0

### PR DESCRIPTION
**Pull request by julianxhokaxhiu**
Hi,

I've noticed that the APNS in this ROM are a bit broken especially for the "Fastweb" carrier in Italy which has totally another mcc and mnc code. I suppose other carriers may have different MCC codes nowaday as the file was last updated in 2016.

What I did I just imported the latest status from the LOS repo.

Would be kind from you if you could merge and trigger another build with this file inside :)

Thanks.

### CODE REVIEW

**Comment by airend** [comment]
Thanks for reporting. We should compare with upstream `device/sample/etc/apns-full-conf.xml`. If that one is also outdated, we'll use your patch.

**Comment by julianxhokaxhiu** [comment]
I did check yesterday that one and it is indeed outdated. The most updated one seems to be from LOS.

Thanks :) I really appreciate your comment.

**Comment by airend** [comment]
So https://android.googlesource.com/device/sample/+/android-9.0.0_r21/etc/apns-full-conf.xml definitely doesn't contain those Fastweb updates, and the rest? In that case, we have to keep it forked here.

**Comment by julianxhokaxhiu** [comment]
I can't talk about the rest but you can compare the informations with this website: http://www.mcc-mnc.com/

And as I know LOS community takes care to update this info often. Google instead leaves this to OEMs to be handled and/or to carriers as, even in the official guide, they talk about using some kind of "country" related APNs list.

**Comment by airend** [comment]
> And as I know LOS community takes care to update this info often. Google instead leaves this to OEMs to be handled and/or to carriers as, even in the official guide, they talk about using some kind of "country" related APNs list.

Yep, I trust their APN changes, just trying to figure out the best way to commit, attribution, etc. In the meantime, I transferred your PR into our Gerrit: https://gerrit.unlegacy-android.org/c/Unlegacy-Android/android_vendor_unlegacy/+/11800 (Change-Id added).

**Pull request closed without merging**
